spring:
  application:
    name: identity-resource-server

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking-realm

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: identity-resource-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.kaleem.identity.*"

server:
  port: 8081

app:
  kafka:
    topic: order-events